#+TITLE: Oh My Emacs GUI
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[https://github.com/xiaohanyu/oh-my-emacs][oh-my-emacs]].

* El-get packages
  :PROPERTIES:
  :CUSTOM_ID: gui-el-get-packages
  :END:

#+NAME: gui-el-get-packages
#+CAPTION: El-get packages for ome-gui module
|                       | Status   | Description                            |
|-----------------------+----------+----------------------------------------|
| [[https://github.com/sellout/emacs-color-theme-solarized.git][color-theme-solarized]] | Required | Adopt this as the default color-theme. |
| [[https://github.com/milkypostman/powerline][powerline]]             | Required | Eye candy for Emacs mode line.         |
| [[https://github.com/m2ym/yascroll-el][yascroll]]              | Required | Eye candy for Emacs scroll bar.        |
| [[https://github.com/coldnew/linum-relative][linum-relative]]        | Required | Eye candy for Emacs linum-mode.        |

* Basic GUI Settings
#+NAME: gui-basics
#+BEGIN_SRC emacs-lisp
  ;; show column number and line number
  (dolist (mode '(column-number-mode line-number-mode))
    (when (fboundp mode) (funcall mode t)))

  ;; Hide scroll-bars
  (scroll-bar-mode -1)
  (horizontal-scroll-bar-mode -1)

  ;; Toggle line highlighting in all buffers except org-mode because linum can't
  ;; handle big files that well
  (global-linum-mode t)
  (add-hook 'org-mode-hook (lambda () (linum-mode 0)))

  ;; Toggle line highlighting in all buffers
  (global-hl-line-mode t)

  ;; if in gui-mode
  (when (display-graphic-p)
    ;; make the fringe thinner (default is 8 in pixels)
    (fringe-mode 4))

  ;; Enable xterm mouse reporting from the terminal
  (unless (display-graphic-p)
    (xterm-mouse-mode t)
    (global-set-key [mouse-4] '(lambda ()
                                 (interactive)
                                 (scroll-down 1)))
    (global-set-key [mouse-5] '(lambda ()
                                 (interactive)
                                 (scroll-up 1))))


  ;; show parenthesis match
  (show-paren-mode 1)
  (setq show-paren-style 'expression)

#+END_SRC
* Choose Source code pro as the Default English Font
  :PROPERTIES:
  :CUSTOM_ID: font
  :END:

Choosing a good and comfortable font is quite important in your whole coding
life. Although the default font of emacs is good enough, I believe there're
better choices. And you can refer to [[http://hivelogic.com/articles/top-10-programming-fonts][TOP 10 PROGRAMMING FONTS]] and [[http://www.sitepoint.com/top-10-programming-fonts/][10 of the
Best Programming Fonts]] to get some feel of various programming fonts.

#+NAME: font
#+BEGIN_SRC emacs-lisp
  ;; frame font
  ;; Setting English Font
  (if (member "Source Code Pro" (font-family-list))
      (set-face-attribute
       'default nil :font "Source Code Pro 9"))
#+END_SRC

* Full screen support
  :PROPERTIES:
  :CUSTOM_ID: fullscreen
  :END:

By default, oh-my-emacs won't bind any shortcut to function keys. There're
two reasons:
- Some special keyboards(such as [[http://en.wikipedia.org/wiki/Happy_Hacking_Keyboard][HHKB]]) lacks function keys.
- Some function keys are occupied by system, either by the windows manager, the
  operating system, or something else which you have no idea to know it before.

Of course you can overrides this convention as you like, oh-my-emacs is just a
starting point.

#+BEGIN_SRC emacs-lisp
;; http://www.emacswiki.org/emacs/FullScreen
(defun ome-toggle-fullscreen ()
  "Toggle full screen"
  (interactive)
  (set-frame-parameter
   nil 'fullscreen
   (when (not (frame-parameter nil 'fullscreen)) 'fullboth)))

  (global-set-key (kbd "<f11>") 'ome-toggle-fullscreen)
#+END_SRC

* Solarized Color Theme
  :PROPERTIES:
  :CUSTOM_ID: color-theme
  :END:

[[http://ethanschoonover.com/solarized][Solarized]] is my favourite color theme. it is available for multiple
applications, not only for emacs. I'll set this as the default theme for
oh-my-emacs.

#+NAME: color-theme
#+BEGIN_SRC emacs-lisp
  (defun ome-solarized-emacs-setup ()
    (load-theme 'solarized-dark t)
    ;; Make underlines more readable on X11
    (if (equal window-system 'x) (setq x-underline-at-descent-line t) ()))

  (ome-install 'solarized-emacs)
#+END_SRC

** Q&A

Q: How to change the default solarized color theme for ome?

A: Just [[http://orgmode.org/worg/org-contrib/babel/intro.html#literate-programming][untangle]]
the related code block by convert =#+BEGIN_SRC emacs-lisp= to =#+BEGIN_SRC
emacs-lisp :tangle no=, and choose any color-theme as you like. Check github
[[https://github.com/xiaohanyu/oh-my-emacs/issues/58][issue]] for detailed discussion.

* Smart mode line
  :PROPERTIES:
  :CUSTOM_ID: powerline
  :END:


#+BEGIN_SRC emacs-lisp
(defun ome-smart-mode-line-setup ()
  (sml/setup)
  (sml/apply-theme 'automatic))

(ome-install 'smart-mode-line)
#+END_SRC

* Yascroll
  :PROPERTIES:
  :CUSTOM_ID: yascroll
  :END:

[[https://github.com/m2ym/yascroll-el][yascroll.el]] is Yet Another Scroll Bar Mode for GNU Emacs.

#+NAME: yascroll
#+BEGIN_SRC emacs-lisp :tangle no
  (defun ome-yascroll-setup ()
    (global-yascroll-bar-mode 1))

(ome-install 'yascroll)
#+END_SRC

* Linum-relative
  :PROPERTIES:
  :CUSTOM_ID: linum-relative
  :END:

I think the inspiration of [[https://github.com/coldnew/linum-relative][linum-relative]] comes from [[https://github.com/myusuf3/numbers.vim][numbers.vim]]. Thanks
[[https://github.com/vimeitor][vimeitor]] for methoning this for me, I tried and I found it's really useful. So
I made it a default for oh-my-emacs.

#+NAME: linum-relative
#+BEGIN_SRC emacs-lisp
(defun ome-linum-relative-setup ()
  (require 'linum-relative))

(ome-install 'linum-relative)
#+END_SRC

* Todo
** Speedbar
- Combine projectile and speedbar to provide a project navigation
  feature. [[https://github.com/rdallasgray/graphene][graphene]] has a solution, which may be worth a try.

** Color-theme
- More color-theme support
  - https://github.com/lvillani/el-monokai-theme
  - https://github.com/chriskempson/tomorrow-theme
  - https://github.com/chriskempson/base16
  - https://github.com/hbin/molokai-theme
